In [17]:
import pandas as pd
import numpy as np
import os.path

In [18]:
os.listdir('Data/')

['Ganjil 2011',
 'Ganjil 2012',
 'Ganjil 2013',
 'Ganjil 2014',
 'Ganjil 2015',
 'Ganjil 2016',
 'Ganjil 2017',
 'Ganjil 2018',
 'Ganjil 2019',
 'Ganjil 2020',
 'Genap 2011',
 'Genap 2012',
 'Genap 2013',
 'Genap 2014',
 'Genap 2015',
 'Genap 2016',
 'Genap 2017',
 'Genap 2018',
 'Genap 2019',
 'Genap 2020']

In [19]:
df = pd.read_csv('Data/Genap 2016/Base_Genap_2016.csv', sep=';')
df.head()

                                              data
0              A,., ,M,U,H, ,S,A,H,I,D, ,T,A,H,I,R
1                                P,e,r,e,m,p,u,a,n
2  S,T,M,I,K, ,W,i,d,y,a, ,C,i,p,t,a, ,D,h,a,r,m,a
3        T,e,k,n,i,k, ,I,n,f,o,r,m,a,t,i,k,a, ,S,1
4                                    1,2,4,3,0,0,5

In [20]:
df.replace(',', '', regex=True, inplace=True)

In [21]:
df.dropna(inplace=True)

In [22]:
# MENGHAPUS NOMOR IJAZAH DAN SEMESTER
df['data'] = df['data'].str.lower()
df = df[df["data"].str.contains("s1ti") == False]
df = df[df["data"].str.contains("no.semesterstatussks") == False]
df = df[df["data"].str.contains("no.semesterkode mata kuliahmata kuliahsks") == False]
df = df[df["data"].str.contains("5520120") == False]
df = df[df["data"].str.contains("/") == False]

df = df[df["data"].str.contains("politeknik negeri samarinda") == False]
df = df[df["data"].str.contains("universitas islam indonesia") == False]
df = df[df["data"].str.contains("stmik asia malang") == False]
df = df[df["data"].str.contains("politeknik negeri bali") == False]
df = df[df["data"].str.contains("stmik balikpapan") == False]
df = df[df["data"].str.contains("politeknik negeri malang") == False]
df = df[df["data"].str.contains("teknik elektronika - d4") == False]
df = df[df["data"].str.contains("teknik informatika - d3") == False]
df = df[df["data"].str.contains("teknik komputer - d3") == False]
df = df[df["data"].str.contains("institut pertanian bogor") == False]
df = df[df["data"].str.contains("universitas komputer indonesia") == False]
df = df[df["data"].str.contains("teknik informatika - s1") == False]
df = df[df["data"].str.contains("stmik dipanegara makassar") == False]
df = df[df["data"].str.contains("universitas negeri surabaya") == False]
df = df[df["data"].str.contains("stmik ppkia tarakanita rahmawati tarakan") == False]
df = df[df["data"].str.contains("universitas gadjah mada") == False]
df = df[df["data"].str.contains("ilmu komputer - s1") == False]
df = df[df["data"].str.contains("sistem informasi - s1") == False]
df = df[df["data"].str.contains("stmik widya cipta dharma") == False]
df = df[df["data"].str.contains("teknik industri - s1") == False]
df = df[df["data"].str.contains("universitas atma jaya yogyakarta") == False]
df = df[df["data"].str.contains("universitas mulawarman") == False]
df = df[df["data"].str.contains("universitas potensi utama") == False]
df = df[df["data"].str.contains("stmik palangka raya") == False]
df = df[df["data"].str.contains("universitas kristen petra") == False]
df = df[df["data"].str.contains("informatika - s1") == False]
df = df[df["data"].str.contains("universitas muhammadiyah kalimantan timur") == False]
#

In [23]:
df.reset_index(inplace=True, drop=True)
df['data'].replace(' ', np.nan, inplace=True)
df['data'].replace('None', np.nan, inplace=True)
df.dropna(inplace=True)
df.mask(df.astype(object).eq('None')).dropna(inplace=True)

In [24]:
df.reset_index(inplace=True, drop=True)
df['data'].replace('None', np.nan, inplace=True)

In [25]:
mark1 = df[df['data'].str[-4:] == '2011'].index
mark2 = df[df['data'].str[-4:] == '2012'].index
mark3 = df[df['data'].str[-4:] == '2013'].index
mark4 = df[df['data'].str[-4:] == '2014'].index
mark5 = df[df['data'].str[-4:] == '2015'].index
mark6 = df[df['data'].str[-4:] == '2016'].index
mark7 = df[df['data'].str[-4:] == '2017'].index
mark8 = df[df['data'].str[-4:] == '2018'].index
mark9 = df[df['data'].str[-4:] == '2019'].index
mark10 = df[df['data'].str[-4:] == '2020'].index
mark11 = df[df['data'].str[-4:] == '2021'].index
mark12 = df[df['data'].str[-4:] == '2022'].index
mark13 = df[df['data'].str[-4:] == '2008'].index
mark14= df[df['data'].str[-4:] == '2009'].index
mark15 = df[df['data'].str[-4:] == '2010'].index
df.drop(mark1, inplace=True)
df.drop(mark2, inplace=True)
df.drop(mark3, inplace=True)
df.drop(mark4, inplace=True)
df.drop(mark5, inplace=True)
df.drop(mark6, inplace=True)
df.drop(mark7, inplace=True)
df.drop(mark8, inplace=True)
df.drop(mark9, inplace=True)
df.drop(mark10, inplace=True)
df.drop(mark11, inplace=True)
df.drop(mark12, inplace=True)
df.drop(mark13, inplace=True)
df.drop(mark14, inplace=True)
df.drop(mark15, inplace=True)
df.reset_index(inplace=True, drop=True)

In [26]:
# # MENGUBAH ROWS KE COLUMNS
# cols=['var'+str(i+1) for i in range(8)]
# #['var1', 'var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8']
# df=pd.DataFrame(df.groupby(df.index//8)['data'].apply(list).values.tolist(),columns=cols)

In [27]:
# df.rename(columns={'var1':'Nama', 'var2':'Jenis_Kelamin', 'var3':'Universitas', 'var4':'Program_Studi', 'var5':'Nim', 
#                     'var6':'Tahun_Masuk', 'var7':'Status_Awal_Mahasiswa', 'var8':'Status_Akhir_Mahasiswa',
#                     'var9':'Tahun_Lulus'}, inplace=True)

In [28]:
# MENGUBAH ROWS KE COLUMNS
cols=['var'+str(i+1) for i in range(7)]
#['var1', 'var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8']
df=pd.DataFrame(df.groupby(df.index//7)['data'].apply(list).values.tolist(),columns=cols)

df.rename(columns={'var1':'Nama', 'var2':'Jenis_Kelamin', 'var3':'Program_Studi', 'var4':'Nim', 
                    'var5':'Tahun_Masuk', 'var6':'Status_Awal_Mahasiswa', 'var7':'Status_Akhir_Mahasiswa',
                    'var8':'Tahun_Lulus'}, inplace=True)

In [29]:
df.loc[250:300]

,Nama,Jenis_Kelamin,Program_Studi,Nim,Tahun_Masuk,Status_Awal_Mahasiswa,Status_Akhir_Mahasiswa
250,eko prasetiyo,laki-laki,teknik informatika s1,1443069,2014 ganjil,peserta didik baru,lulus
251,eko susanto,laki-laki,teknik informatika s1,1643012,2016 ganjil,peserta didik baru,aktif
252,eldhy pramana putra,laki-laki,teknik informatika s1,1043008,2010 ganjil,peserta didik baru,mengundurkan diri
253,elvi sanggalangi,perempuan,teknik informatika s1,1643151,2016 ganjil,peserta didik baru,aktif
254,elvira,perempuan,teknik informatika s1,1343111,2013 ganjil,peserta didik baru,mengundurkan diri
255,embie lintang listianto,laki-laki,teknik informatika s1,1643015,2016 ganjil,peserta didik baru,aktif
256,endang sri wahyuni,perempuan,teknik informatika s1,1643145,2016 ganjil,peserta didik baru,lulus
257,endi ismanto,laki-laki,teknik informatika s1,1343030,2013 ganjil,peserta didik baru,mengundurkan diri
258,endro adhi sulistyono,laki-laki,teknik informatika s1,1543141,2015 ganjil,peserta didik baru,lulus
259,enes purwo saputro,perempuan,teknik informatika s1,1143122,2011 ganjil,peserta didik baru,lulus
260,engga renata,laki-laki,teknik informatika s1,1443058,2014 ganjil,peserta didik baru,lulus
261,erdi nurikhsan,laki-laki,teknik informatika s1,1543102,2015 ganjil,peserta didik baru,lulus
262,erfanie mahmud,laki-laki,teknik informatika s1,1243040,2012 ganjil,peserta didik baru,lulus
263,erika pratiwi,perempuan,teknik informatika s1,1643173,2016 ganjil,peserta didik baru,lulus
264,eriko pebriyono,laki-laki,teknik informatika s1,1643121,2016 ganjil,peserta didik baru,aktif
265,erna try wahyuni,perempuan,teknik informatika s1,1543051,2015 ganjil,peserta didik baru,aktif
266,erwin,laki-laki,teknik informatika s1,1543035,2015 ganjil,peserta didik baru,aktif
267,erwin mattoreang,laki-laki,teknik informatika s1,0943096,2009 ganjil,peserta didik baru,mengundurkan diri
268,eva noryanti,perempuan,teknik informatika s1,1543101,2015 ganjil,peserta didik baru,lulus
269,evan risqiandi,laki-laki,teknik informatika s1,1443916,2014 ganjil,pindahan,aktif
270,evi erviana,perempuan,teknik informatika s1,0943031,2009 ganjil,peserta didik baru,mengundurkan diri
271,evindo valen dista palimpin,laki-laki,teknik informatika s1,1443108,2014 ganjil,peserta didik baru,lulus
272,fadhila apriliai firdausi,perempuan,teknik informatika s1,1443042,2014 ganjil,peserta didik baru,lulus
273,fahmi ferri irawan,laki-laki,teknik informatika s1,1343108,2013 ganjil,peserta didik baru,mengundurkan diri
274,fahmi januartha,laki-laki,teknik informatika s1,1343006,2013 ganjil,peserta didik baru,lulus
275,faisal,perempuan,teknik informatika s1,1143150,2011 ganjil,peserta didik baru,mengundurkan diri
276,fajar dewa chrisna,laki-laki,teknik informatika s1,1543085,2015 ganjil,peserta didik baru,aktif
277,fajar nurdin djabar,laki-laki,teknik informatika s1,1043110,2010 ganjil,peserta didik baru,mengundurkan diri
278,fajar nurhadi,perempuan,teknik informatika s1,1143129,2011 ganjil,peserta didik baru,lulus
279,fajar ramadani,laki-laki,teknik informatika s1,1643112,2016 ganjil,peserta didik baru,aktif
280,fajar susanto,laki-laki,teknik informatika s1,0943120,2009 ganjil,peserta didik baru,mengundurkan diri
281,fakhrizal amri,laki-laki,teknik informatika s1,1643146,2016 ganjil,peserta didik baru,aktif
282,faqih fahrunika pamungkas,laki-laki,teknik informatika s1,1243106,2012 ganjil,peserta didik baru,mengundurkan diri
283,farhan syaulani,laki-laki,teknik informatika s1,0843041,2008 ganjil,peserta didik baru,mengundurkan diri
284,farid rukmana,laki-laki,teknik informatika s1,0943108,2009 ganjil,peserta didik baru,mengundurkan diri
285,fariz alfrizal,laki-laki,teknik informatika s1,1643904,2016 ganjil,pindahan,aktif
286,fariz mirza ahmad,laki-laki,teknik informatika s1,1643100,2016 ganjil,peserta didik baru,aktif
287,febrian noor,laki-laki,teknik informatika s1,1543018,2015 ganjil,peserta didik baru,lulus
288,febry junaidi putra,laki-laki,teknik informatika s1,1643046,2016 ganjil,peserta didik baru,aktif
289,febryana anggraini,perempuan,teknik informatika s1,1243155,2012 ganjil,peserta didik baru,lulus
290,febryanto kusnadi ridwan,laki-laki,teknik informatika s1,1543123,2015 ganjil,peserta didik baru,aktif
291,feggy wardanny,laki-laki,teknik informatika s1,1643078,2016 ganjil,peserta didik baru,aktif
292,fendy apriliawan,laki-laki,teknik informatika s1,1543027,2015 ganjil,peserta didik baru,aktif
293,ferdhy surya pratama,laki-laki,teknik informatika s1,1543905,2015 ganjil,pindahan,lulus
294,fernando bagus nugraha,laki-laki,teknik informatika s1,1243061,2012 ganjil,peserta didik baru,mengundurkan diri
295,ferry dimas pratama w,laki-laki,teknik informatika s1,0943141,2009 ganjil,peserta didik baru,mengundurkan diri
296,fery irawan,laki-laki,teknik informatika s1,1543114,2015 ganjil,peserta didik baru,aktif
297,fildzha vanessa,perempuan,teknik informatika s1,1443109,2014 ganjil,peserta didik baru,mengundurkan diri
298,firdaus adi frimana,laki-laki,teknik informatika s1,1343078,2013 ganjil,peserta didik baru,mengundurkan diri
299,firdaus ali,laki-laki,teknik informatika s1,1443078,2014 ganjil,peserta didik baru,aktif
300,firman arif gunawan,laki-laki,teknik informatika s1,1643154,2016 ganjil,peserta didik baru,aktif

In [30]:
df.shape

(899, 7)

In [31]:
df.tail()

,Nama,Jenis_Kelamin,Program_Studi,Nim,Tahun_Masuk,Status_Awal_Mahasiswa,Status_Akhir_Mahasiswa
894,zulfatjrin,laki-laki,teknik informatika s1,1643045,2016 ganjil,peserta didik baru,aktif
895,zulfikar fitri istyanto,laki-laki,teknik informatika s1,1243042,2012 ganjil,peserta didik baru,lulus
896,zulfikhsa amrullah,perempuan,teknik informatika s1,1143128,2011 ganjil,peserta didik baru,lulus
897,zulkarnain sudirman,laki-laki,teknik informatika s1,1643009,2016 ganjil,peserta didik baru,lulus
898,zulkhaidir rochandi yusuf,laki-laki,teknik informatika s1,1243045,2012 ganjil,peserta didik baru,lulus

In [32]:
df.to_csv('Data/Genap 2016/Data_Genap_2016.csv')